image: debian:stable-slim

variables:
  GIT_STRATEGY: fetch
  EVM_EMACS: emacs-26.3

before_script:
  - apt update -qq
  - DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y -qq -o=Dpkg::Use-Pty=0 git curl python
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH

  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

  # Use cask to install development dependencies
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=$HOME/.cask/bin:$PATH
  - cask

stages:
  - test

test-all:
  stage: test
  script:
    - cask exec test/run --debug
