image:  silex/emacs:26.3

variables:
  GIT_STRATEGY: fetch
  EVM_EMACS: emacs-26.3

before_script:
  - apt update -qq
  - DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y -qq -o=Dpkg::Use-Pty=0 git curl python ca-certificates ruby texinfo build-essential

stages:
  - test

test-all:
  stage: test
  script:
    - make test
